//
// Copyright (c) Sergey Borodavkin. All rights reserved.
// Licensed under the MIT License. See LICENSE file in the project root
// for full license information.
//

#include <stdint.h>
#include <string.h>
#include "charset.h"
#include "mapcoll.h"


uint8_t LEVEL_ART[NUM_LEVEL_ART][16] = {
  { 0, 1, 0, 1, CHAR_GOLD_1, CHAR_GOLD_2, CHAR_GOLD_3, CHAR_GOLD_4,
      CHAR_WBL_GOLD_1, CHAR_WBL_GOLD_2, CHAR_WBL_GOLD_3, CHAR_WBL_GOLD_4,
      CHAR_EMERALD_1, CHAR_EMERALD_2, CHAR_EMERALD_3, CHAR_EMERALD_4},
  { CHAR_MAZE_LVL2_1, CHAR_MAZE_LVL2_2, CHAR_MAZE_LVL2_3, CHAR_MAZE_LVL2_4,
    CHAR_GOLD_LVL2_1, CHAR_GOLD_LVL2_2, CHAR_GOLD_LVL2_3, CHAR_GOLD_LVL2_4,
    CHAR_WBL_GOLD_LVL2_1, CHAR_WBL_GOLD_LVL2_2, CHAR_WBL_GOLD_LVL2_3, CHAR_WBL_GOLD_LVL2_4,
    CHAR_EMERALD_LVL2_1, CHAR_EMERALD_LVL2_2, CHAR_EMERALD_LVL2_3, CHAR_EMERALD_LVL2_4 },
  { CHAR_MAZE_LVL3_1, CHAR_MAZE_LVL3_2, CHAR_MAZE_LVL3_3, CHAR_MAZE_LVL3_4,
    CHAR_GOLD_LVL3_1, CHAR_GOLD_LVL3_2, CHAR_GOLD_LVL3_3, CHAR_GOLD_LVL3_4,
    CHAR_WBL_GOLD_LVL3_1, CHAR_WBL_GOLD_LVL3_2, CHAR_WBL_GOLD_LVL3_3, CHAR_WBL_GOLD_LVL3_4,
    CHAR_EMERALD_LVL3_1, CHAR_EMERALD_LVL3_2, CHAR_EMERALD_LVL3_3, CHAR_EMERALD_LVL3_4 },
  { CHAR_MAZE_LVL4_1, CHAR_MAZE_LVL4_2, CHAR_MAZE_LVL4_3, CHAR_MAZE_LVL4_4,
    CHAR_GOLD_LVL4_1, CHAR_GOLD_LVL4_2, CHAR_GOLD_LVL4_3, CHAR_GOLD_LVL4_4,
    CHAR_WBL_GOLD_LVL4_1, CHAR_WBL_GOLD_LVL4_2, CHAR_WBL_GOLD_LVL4_3, CHAR_WBL_GOLD_LVL4_4,
    CHAR_EMERALD_LVL4_1, CHAR_EMERALD_LVL4_2, CHAR_EMERALD_LVL4_3, CHAR_EMERALD_LVL4_4 },
  { CHAR_MAZE_LVL5_1, CHAR_MAZE_LVL5_2, CHAR_MAZE_LVL5_3, CHAR_MAZE_LVL5_4,
    CHAR_GOLD_LVL5_1, CHAR_GOLD_LVL5_2, CHAR_GOLD_LVL5_3, CHAR_GOLD_LVL5_4,
    CHAR_WBL_GOLD_LVL5_1, CHAR_WBL_GOLD_LVL5_2, CHAR_WBL_GOLD_LVL5_3, CHAR_WBL_GOLD_LVL5_4,
    CHAR_EMERALD_LVL5_1, CHAR_EMERALD_LVL5_2, CHAR_EMERALD_LVL5_3, CHAR_EMERALD_LVL5_4 },
  { CHAR_MAZE_LVL6_1, CHAR_MAZE_LVL6_2, CHAR_MAZE_LVL6_3, CHAR_MAZE_LVL6_4,
    CHAR_GOLD_LVL6_1, CHAR_GOLD_LVL6_2, CHAR_GOLD_LVL6_3, CHAR_GOLD_LVL6_4,
    CHAR_WBL_GOLD_LVL6_1, CHAR_WBL_GOLD_LVL6_2, CHAR_WBL_GOLD_LVL6_3, CHAR_WBL_GOLD_LVL6_4,
    CHAR_EMERALD_LVL6_1, CHAR_EMERALD_LVL6_2, CHAR_EMERALD_LVL6_3, CHAR_EMERALD_LVL6_4 }
};

uint8_t LEVEL_ART_PEN_COLOR[NUM_LEVEL_ART] = { 0x0F, 0x0F, 0x0F, 0x0F, 0x0E, 0x0F };


void load_wobble_gold_chars(void) {
  // Overwrite alphabet with wobble charset.
  memcpy((uint8_t*)(CHARSET_START+CHARSET_SIZE),
      (uint8_t*)GOLD_WOBBLE_CHARSET, GOLD_WOBBLE_CHARSET_SIZE);
}


void unload_wobble_gold_chars(void) {
  // Copy backup buffer to alphabet location  
  memcpy((uint8_t*)(CHARSET_START+CHARSET_SIZE),
      (uint8_t*)(GOLD_WOBBLE_CHARSET+GOLD_WOBBLE_CHARSET_SIZE), GOLD_WOBBLE_CHARSET_SIZE);
}

void backup_alphabet(void) {  
  // Backup alphabet to GOLD_WOBBLE_CHARSET+192
  memcpy((uint8_t*)(GOLD_WOBBLE_CHARSET+GOLD_WOBBLE_CHARSET_SIZE),
      (uint8_t*)(CHARSET_START+CHARSET_SIZE), GOLD_WOBBLE_CHARSET_SIZE); 
}